### ISSUE TITLE
kind cluster does not have a default despite docs saying so

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/stackablectl#5]
The docs say that the default cluster name will be `stackable-data-platform` but if I try to create a cluster without giving a name it fails:

```
./stackablectl-x86_64-unknown-linux-gnu release install -k alpha-3
error: The following required arguments were not provided:
    <RELEASE>

USAGE:
    stackablectl-x86_64-unknown-linux-gnu release install --kind-cluster [<KIND_CLUSTER>] <RELEASE>
```

This works:
```
./stackablectl-x86_64-unknown-linux-gnu release install -k foobar alpha-3
```

**Comment by sbernauer** [comment]
It works if you put the `-k` option at the end because if matches 0 or 1 argument. If you say `./stackablectl-x86_64-unknown-linux-gnu release install -k alpha-3` the `alpha-3` is matched as kind cluster name and than the release name is missing.
I guess i will split it in two options: `-k|--kind` as bool flag whether to spin up kind cluster and an option `--kind-cluster-name` to overwrite the default name
Ack?
